### ISSUE TITLE
Dependency problem with pip install

### ISSUE THREAD

**Issue by squintfox** [ServiceNow/PySNC#101]
In the pyproject.toml, it defines this:
https://github.com/ServiceNow/PySNC/blob/f1fed33bfb11960b8bbb135473f3ae2d8eba001f/pyproject.toml#L19-L24
The carat is causing the required pip version to be required at >=23.3.1<24.0.0.  Since pip 24.0.0 is already released, anyone that's already updated pip can no longer install 1.1.6 without a forced downgrade.

Maybe >= would be better than carat if there's a pip dependency in 23.x?
```[tasklist]
### Tasks
```

**Comment by vetsin** [comment]
You're right, no reason. Been busy this week I'll try to get this updated soon.

**Comment by squintfox** [comment]
@vetsin Awesome, thank you.
