### ISSUE TITLE
Export Query and QueryCondition classes

### ISSUE THREAD

**Issue by Xumeiquer** [ServiceNow/PySNC#40]
By exporting `Query` and `QueryCondition` classes in the `__init__.py` file will help to create custom queries programatically.

```python
from pysnc import Query, QueryCondition, GlideRecord

# Using Query
q = Query("incident")

q.add_active_query()
q.add_query("description", "=", "123456")

raw_query = q.generate_query()

gr = GlideRecord("ServiceNowClient", "incident")

gr.add_encoded_query(raw_query)

# Using now the QueryCondition
q = QueryCondition("description", "CONTAINS", "testing")
q.add_or_query("impact", "=", "2")

raw_condition = q.generate()

gr = GlideRecord("instance", "incident")
gr.add_encoded_query(raw_query)
```

Another important point will be to unify the interface for Query and QueryCondition. Perhaps, `Query.generate_query()` and `QueryCondition.generate()`

**Comment by vetsin** [comment]
good idea/point - i'll see what makes sense

**Comment by vetsin** [comment]
See https://github.com/ServiceNow/PySNC/blob/master/test/test_snc_api_query.py#L195 for use
