### ISSUE TITLE
implementing set_new_guid_value

### ISSUE THREAD

**Issue by peterbayerle** [ServiceNow/PySNC#42]
I see in the dev notes this hasn’t been implemented yet. But it’s not marked as “not possible”, so it seems to be possible. I’m having trouble finding resources online for doing this. Does anyone know the API request to do a set_new_guid_value on a record in service now? If someone can point me in the right direction, I can help implement. thanks

**Comment by vetsin** [comment]
@peterbayerle I will test this next week - but I would presume that if it's possible you would be able to just set the sys_id directly before insert.

```
gr.initalize()
gr.sys_id = ...
...
gr.insert()
```

**Comment by vetsin** [comment]
@peterbayerle confirmed this works - i'll add the convenience method for the next release

Make sure the sys_id you set is 32 bytes though. e.g.:

```
        gr = client.GlideRecord('problem')
        gr.initialize()
        customsysid = 'AAAABBBBCCCCDDDDEEEEFFFF00001111'
        gr.sys_id = customsysid
        gr.short_description = "Unit Test - Test insert id update"
        res = gr.insert()
        self.assertIsNotNone(res)
        self.assertIsNotNone(gr.sys_id)
        self.assertEquals(res, customsysid)
        # make sure it exists
        gr2 = client.GlideRecord('problem')
        self.assertTrue(gr2.get(customsysid))
````

this passes.
