### ISSUE TITLE
Dor walking reference fields

### ISSUE THREAD

**Issue by rodrigorenie** [ServiceNow/PySNC#50]
Hello, first of all, amazing work on this API! I've just started using it today and it already helped me A LOT.

For my question: does it support dot walking the reference fields, like `gr.caller_id.user_name`? It seems that `caller_id` is simply a string and not an object pointing to the `sys_user`, or am I wrong?

**Comment by vetsin** [comment]
@rodrigorenie yes and no - you cannot dotwalk something already queried but you can specify the dot walk before you query. So:

> gr.fields = 'caller_id,caller_id.user_name'
> gr.query()
> ...
> gr.get_value('caller_id.user_name')

Will work fine. Keeping this open to explicitly test/doc that.

**Comment by vetsin** [comment]
Improved this with the newest version ( unreleased as of this comment ) and added docs on the topic
