### ISSUE TITLE
Provide join_queries that look through cmdb_rel_ci

### ISSUE THREAD

**Issue by arthurzenika** [ServiceNow/PySNC#54]
I'm trying to extract data from two tables that are linked using `cmdb_rel_ci`. I was expecting to be able to add a join_query as described by https://servicenow.github.io/PySNC/user/advanced.html#join-queries but it seems that this is a functionality to query linked or dotwalked attributes (not sure how they are called in servicenow - reference field?) with `join_table_field`. 

This is pseudo code I would like to be able to write :  

```
gr = client.GlideRecord('cmdb_ci_server')
join_query = gr.add_join_query('cmdb_ci_ip_address', join_relationship_field='Owned by::Owns')
gr.query()
```
Inspired by schema https://docs.servicenow.com/en-US/bundle/tokyo-servicenow-platform/page/product/configuration-management/concept/class-server.html 

That would return records of `servers` with their related `ip_address`. 

Is this already possible with the existing code ?

**Comment by vetsin** [comment]
looking at the schema you probably want something more like 

```
gr = client.GlideRecord('cmdb_ci_server')
gr.add_join_query('cmdb_ci_ip_address', join_relationship_field='cmdb_ci')
```

**Comment by vetsin** [comment]
honestly a join query is unlikely what you want here. I would recommend querying the individual tables - though I cannot help there as I'm wholly unfamiliar with CMDB. Seeing however as there is no issue with the API I'm going to close this - if there are particular data questions I suggest asking within the ServiceNow community
