### ISSUE TITLE
Attachments Get is Broken

### ISSUE THREAD

**Issue by brolewis** [ServiceNow/PySNC#75]
```
attachment = self.client.Attachment(raw_case["sys_class_name"])
attachment.get(raw_case["sys_id"])
```
<img width="922" alt="image" src="https://user-images.githubusercontent.com/1481911/235734430-e0936e71-82f6-45cc-bdf7-d24ebcf7ea71.png">

**Comment by brolewis** [comment]
Also, of note, this is a change in the API behavior that I did not see documented anywhere since the class no longer accepts `sys_id`.

**Comment by vetsin** [comment]
@brolewis sorry about that, that's pretty annoying of me to change. I'll add the right tests and fix asap.

Do you *want* me to keep the older behavior? it's inconsistent with everything else but does no harm

**Comment by brolewis** [comment]
@vetsin As long as I know the right way to do it, I'm fine with the `get` method, and honestly that makes sense to go that route, as long as it works :)
