### ISSUE TITLE
Support for refresh_token grant type for OAuth2

### ISSUE THREAD

**Issue by d1vya-rede** [ServiceNow/PySNC#91]
Support for refresh_token grant type for OAuth2: https://docs.servicenow.com/bundle/vancouver-platform-security/page/administer/security/reference/r_OAuthAPIRequestParameters.html

Not sure, if this is already supported but could not find any means to confirm that.

**Comment by d1vya-rede** [comment]
@vetsin Would you be able to please confirm if this is supported already? 🙇‍♀️

**Comment by vetsin** [comment]
@d1vya-rede [Password Grant Flow](https://servicenow.github.io/PySNC/user/authentication.html#oauth2-password-grant-flow) uses it -- one uses `password` to grant a refresh and bearer token and it manages them.

**Comment by d1vya-rede** [comment]
@vetsin Got it. But is there a way to only use the grant_type = refresh_token means of Auth where we only pass on **client_id**, **client_secret**, **access_token** & **refresh_token**?

something like the below example for this docs: https://docs.servicenow.com/bundle/vancouver-platform-security/page/administer/security/reference/r_OAuthAPIRequestParameters.html

```
$ curl -d"grant_type=refresh_token&client_id=be3aeb583ace210011c15b24a43e25d8
&client_secret=client_password
&refresh_token=w599voG89897rGVDmdp12WA681r9E5948c1CJTPi8g4HGc4NWaz62k6k1K0FMxHW40H8yOO3Hoe" 
https://instancename.service-now.com/oauth_token.do
```
