### ISSUE TITLE
Bulk extract fails with `Maximum Execution time exceeded`

### ISSUE THREAD

**Issue by d1vya-rede** [ServiceNow/PySNC#95]
I am trying to Bulk extract a table with a lot of data (last 7 months based on sys_created_on). The extraction fails with `Maximum Execution time exceeded` from [here](https://github.com/ServiceNow/PySNC/blob/505ca4e937caa867a0f47b36374ac9cc87d23c22/pysnc/record.py#L536). 

I used to use [this](https://github.com/rbw/pysnow) other wrapper on top of ServiceNow API which used to provide means to use the `limit` param which could help with fetching larger volumes data. Is there any similar means to do the same using PySNC without having to make multiple calls to `Gliderecord` for shorter amounts of data?

**Comment by vetsin** [comment]
Looking at [Performance Concerns](https://servicenow.github.io/PySNC/user/advanced.html#performance-concerns) may help you.

But to directly answer your question, yes, decrease the [batch size](https://servicenow.github.io/PySNC/api.html#pysnc.GlideRecord) to something like `10`. Your error is from servicenow itself timing out trying to generate a huge response, so make each response smaller.
