### ISSUE TITLE
Get Table column metadata

### ISSUE THREAD

**Issue by d1vya-rede** [ServiceNow/PySNC#97]
Is there a way to get the column metadata to derive (data types, scale, precision etc..)?

**Comment by vetsin** [comment]
The only way you could is if you had the permissions to query the sys_dictonary table to manually query the types. But as this is a rest API and JSON nothing is actually typed beyond string or bool.

**Comment by d1vya-rede** [comment]
Thanks. I was able to get what I was looking for.
